name: tracely
description: Fully fledged management app with cloud synchronization. Keep track of your projects, ideas, expenses, notes - and everything you can think of.
version: 1.3.0

publish_to: 'none'

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Time formatting
  intl: ^0.18.1

  # Firebase Plugins
  firebase_core: ^2.15.0
  firebase_auth: ^4.9.0
  firebase_database: ^10.2.4

  # Sign in platforms
  google_sign_in: ^6.1.5
 
  # Connectivity checker
  connectivity_plus: ^4.0.2

  # Markdown Editable Text Input for notes
  markdown_editable_textinput: ^2.1.0 # Never to be updated. It does not work.
  flutter_markdown: ^0.6.17+2

  # Lottie for animations
  lottie: ^2.6.0

  # Google Fonts! A library of fonts used across the app
  google_fonts: ^6.0.0

  # Slidables ~ used for Checklists & checkboxes
  flutter_slidable: ^3.0.0

  # Pie Chart ~ used for Expenses
  pie_chart: ^5.3.2

  # Encrypt ~ used to encrypt notes with AES
  encrypt: ^5.0.1

  # URL Launcher ~ used for homepage's buttons
  url_launcher: ^6.1.14
  url_launcher_web: ^2.0.20
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/images/
    - assets/animations/